enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 2

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Change form factor' 'Hide timestamp' 'Miniplayer' 'Custom player overlay opacity' 'Return YouTube Dislike' 'Open Shorts in regular player' 'Change start page' 'Announcements' 'Enable debugging' 'Check watch history domain name resolution' 'Disable HDR video' 'Playback speed'"

[Spotify]
apkmirror-dlurl = "https://apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
